name       : rapid-photo-downloader
version    : 0.9.28
release    : 23
source     :
    - https://launchpad.net/rapid/pyqt/0.9.28/+download/rapid-photo-downloader-0.9.28.tar.gz : 64a8454529a3bb13921d6b9a7f41eb02984f237690c71d247dbf0379854a8eff
homepage   : https://www.damonlynch.net/rapid/
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Rapid Photo Downloader for Linux
description: |
    Rapid Photo Downloader imports photos and videos from cameras, phones, memory cards and other devices at high speed. It can be configured to rename photos and videos with meaningful filenames you specify. It can also back up photos and videos as they are downloaded. It downloads from and backs up to multiple devices simultaneously.
rundeps    :
    - gexiv2
    - ifuse
    - perl-image-exiftool
    - pymediainfo
    - pyprind
    - python-arrow
    - python-babel
    - python-colorlog
    - python-colour
    - python-easygui
    - python-gobject
    - python-gphoto2
    - python-pyheif
    - python-pyzmq
    - python-requests
    - python-show-in-file-manager
    - python-sortedcontainers
    - python-tenacity
    - python3-qt5
    - qt5-imageformats
build      : |
    %python3_setup
install    : |
    %python3_install
