name       : rapid-photo-downloader
version    : 0.9.10
release    : 11
source     :
    - https://launchpad.net/rapid/pyqt/0.9.10/+download/rapid-photo-downloader-0.9.10.tar.gz : ae498a0805353d28d3b77992f61476a1984fccd03495de5f22ca3bfb927414c4
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Rapid Photo Downloader for Linux
description: |
    Rapid Photo Downloader imports photos and videos from cameras, phones, memory cards and other devices at high speed. It can be configured to rename photos and videos with meaningful filenames you specify. It can also back up photos and videos as they are downloaded. It downloads from and backs up to multiple devices simultaneously.
rundeps    :
    - gexiv2
    - perl-image-exiftool
    - pymediainfo
    - python-arrow
    - python-colorlog
    - python-colour
    - python-easygui
    - python-gphoto2
    - python-psutil
    - python-pyzmq
    - python-rawkit
    - python-sortedcontainers
    - python-tornado
    - python3-qt5
    - pyprind
    - pyxdg
setup      : |
    %python3_setup
install    : |
    %python3_install
