name       : rapid-photo-downloader
version    : 0.9.24
release    : 19
source     :
    - https://launchpad.net/rapid/pyqt/0.9.24/+download/rapid-photo-downloader-0.9.24.tar.gz : 66b9482c9212043b519416982dacd734f8d05c285eb8d7e3ee3f0d7a29068590
homepage   : https://www.damonlynch.net/rapid/
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Rapid Photo Downloader for Linux
description: |
    Rapid Photo Downloader imports photos and videos from cameras, phones, memory cards and other devices at high speed. It can be configured to rename photos and videos with meaningful filenames you specify. It can also back up photos and videos as they are downloaded. It downloads from and backs up to multiple devices simultaneously.
rundeps    :
    - gexiv2
    - perl-image-exiftool
    - pymediainfo
    - python-arrow
    - python-babel
    - python-colorlog
    - python-colour
    - python-easygui
    - python-gphoto2
    - python-psutil
    - python-pyheif
    - python-pyzmq
    - python-rawkit
    - python-requests
    - python-sortedcontainers
    - python-tenacity
    - python3-qt5
    - pyprind
    - pyxdg
setup      : |
    %python3_setup
install    : |
    %python3_install
