name       : rapid-photo-downloader
version    : 0.9.13
release    : 13
source     :
    - https://launchpad.net/rapid/pyqt/0.9.13/+download/rapid-photo-downloader-0.9.13.tar.gz : 407e0ddca01c655a6069d6d658c0d56085c67a5c4b4a741a7f81c6ae51e02794
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Rapid Photo Downloader for Linux
description: |
    Rapid Photo Downloader imports photos and videos from cameras, phones, memory cards and other devices at high speed. It can be configured to rename photos and videos with meaningful filenames you specify. It can also back up photos and videos as they are downloaded. It downloads from and backs up to multiple devices simultaneously.
rundeps    :
    - gexiv2
    - perl-image-exiftool
    - pymediainfo
    - python-arrow
    - python-colorlog
    - python-colour
    - python-easygui
    - python-gphoto2
    - python-psutil
    - python-pyzmq
    - python-rawkit
    - python-sortedcontainers
    - python-tornado
    - python3-qt5
    - pyprind
    - pyxdg
setup      : |
    %python3_setup
install    : |
    %python3_install
