name       : rapid-photo-downloader
version    : 0.9.18
release    : 17
source     :
    - https://launchpad.net/rapid/pyqt/0.9.18/+download/rapid-photo-downloader-0.9.18.tar.gz : 7c792b2756857a408422047b5cfca1efb484722b9230db4b5db86ef3b4d6e796
homepage   : https://www.damonlynch.net/rapid/
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Rapid Photo Downloader for Linux
description: |
    Rapid Photo Downloader imports photos and videos from cameras, phones, memory cards and other devices at high speed. It can be configured to rename photos and videos with meaningful filenames you specify. It can also back up photos and videos as they are downloaded. It downloads from and backs up to multiple devices simultaneously.
rundeps    :
    - gexiv2
    - perl-image-exiftool
    - pymediainfo
    - python-arrow
    - python-colorlog
    - python-colour
    - python-easygui
    - python-gphoto2
    - python-psutil
    - python-pyzmq
    - python-rawkit
    - python-sortedcontainers
    - python-tenacity
    - python3-qt5
    - pyprind
    - pyxdg
setup      : |
    %python3_setup
install    : |
    %python3_install
