name       : rapid-photo-downloader
version    : 0.4.11
release    : 1
source     :
    - http://launchpad.net/rapid/trunk/0.4.11/+download/rapid-photo-downloader-0.4.11.tar.gz : 57396807458dea457e814b1ba021d69378af3ca310c44800ccb150d3cbace911
license    : GPL-3.0
component  : multimedia.graphics
summary    : Rapid Photo Downloader for Linux
description: |
    Rapid Photo Downloader imports photos and videos from cameras, phones, memory cards and other devices at high speed. It can be configured to rename photos and videos with meaningful filenames you specify. It can also back up photos and videos as they are downloaded. It downloads from and backs up to multiple devices simultaneously.
rundeps  : 
    - python-gtk2
    - python-pillow
    - gnome-python
    - notify-python
    - pyexiv2
    - librsvg
    - perl-image-exiftool
    - ffmpegthumbnailer
    - kaa-metadata
build      : |
    %python_setup
install    : |
    %python_install
    rm -rf $installdir/usr/share/kde4
